resolver: lts-16.1
packages:
- .

extra-deps:
- git: https://github.com/fpclass/slack
  commit: 51f78ac6c27241e359a4f7f2de594714a71421b7
- git: https://github.com/mbg/uow-apis
  commit: 2dec278bb7a83a0b2a74150abbb1fc70177a436a
